services:
  FavLitModerationApi:
    image: maxbqb/favorite-literature-moderation-api:latest
    environment:
      - DB_HOST=FavLitModerationApiDb
      - DB_NAME=$MODERATION_DB_NAME
      - DB_USERNAME=$MODERATION_DB_USERNAME
      - DB_PASSWORD=$MODERATION_DB_PASSWORD
      - MQTT_HOST=rabbitmq
    ports:
      - 8080:8080
    depends_on:
      - FavLitModerationApiDb
      - rabbitmq
  FavLitModerationApiDb:
    image: postgres:latest
    volumes:
      - favorite_literature_moderation_api_db_volume:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=$MODERATION_DB_PASSWORD
      - POSTGRES_USER=$MODERATION_DB_USERNAME
      - POSTGRES_DB=$MODERATION_DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management-alpine
version: '3'
volumes:
  favorite_literature_moderation_api_db_volume:
    driver: local