services:
  FavLitModerationApiDb:
    image: postgres:latest
    volumes:
      - favorite_literature_moderation_api_db_volume:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 30432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
version: '3'
volumes:
  favorite_literature_moderation_api_db_volume:
    driver: local